datasource:
  driverName: mysql
  dataSourceName: root:qzzx91112@tcp(127.0.0.1:3306)/douyin_team
redis:
  host: localhost
  port: 6379
  password:
server:
  port: 8080

# 视频的存放地址
video:
  videoUrl: https://hzbucket-1312272501.cos.ap-guangzhou.myqcloud.com/videos/  # 这个是获取视频流服务器的接口地址
  imageUrl: https://hzbucket-1312272501.cos.ap-guangzhou.myqcloud.com/pictures/ #服务器上传文件并没有这封面好像
  filePath: upload/ # 如果存放本机的话 这个就是服务器中视频存放的目录

cos:
  SecretId: SecretId
  SecretKey: SecretKey
  url: https://hzbucket-1312272501.cos.ap-guangzhou.myqcloud.com